version: '3.6'

services:
  master:
    image: redis:5.0.6-alpine
    container_name: haredis
    command: ['/usr/local/etc/redis/redis.conf']
    volumes:
      - './data/master:/data'
      - './config/redis1.conf:/usr/local/etc/redis/redis.conf'
  replica1:
    image: redis:5.0.6-alpine
    container_name: replica1
    command: ['/usr/local/etc/redis/redis.conf']
    volumes:
      - './data/slave1:/data'
      - './config/replica1.conf:/usr/local/etc/redis/redis.conf'
  replica2:
    image: redis:5.0.6-alpine
    container_name: replica2
    command: ['/usr/local/etc/redis/redis.conf']
    volumes:
      - './data/slave2:/data'
      - './config/replica2.conf:/usr/local/etc/redis/redis.conf'
  sentinel1:
    image: redis:5.0.6-alpine
    container_name: sentinel1
    entrypoint: ['redis-sentinel']
    command: ['/usr/local/etc/redis/sentinel.conf']
    volumes:
      - './config/sentinel1.conf:/usr/local/etc/redis/sentinel.conf'
  sentinel2:
    image: redis:5.0.6-alpine
    container_name: sentinel2
    entrypoint: ['redis-sentinel']
    command: ['/usr/local/etc/redis/sentinel.conf']
    volumes:
      - './config/sentinel2.conf:/usr/local/etc/redis/sentinel.conf'
  sentinel3:
    image: redis:5.0.6-alpine
    container_name: sentinel3
    entrypoint: ['redis-sentinel']
    command: ['/usr/local/etc/redis/sentinel.conf']
    volumes:
      - './config/sentinel3.conf:/usr/local/etc/redis/sentinel.conf'
